[llvm]
link-shared = true

[build]
target = ["powerpc64le-unknown-linux-gnu"]
cargo = "/usr/bin/cargo"
rustc = "/usr/bin/rustc"
python = "python"
extended = true
sanitizers = false
profiler = true
local-rebuild = false 
full-bootstrap = true 


[install]
prefix = "/usr"

[rust]
# 0 or the new default of 16 is faster, but can result in worse performance
# https://github.com/rust-lang/rust/issues/47745
codegen-units = 1
codegen-units-std = 1
channel = "stable"
rpath = false
optimize = true
debug = false
debuginfo-level = 0 

[target.powerpc64le-unknown-linux-gnu]
llvm-config = "/usr/bin/llvm-config"
